### PR TITLE
General dashboard improvements

### PR DESCRIPTION
**Pull request by carissaallen**
### Overview
Updates the layout to the Dashboard page, adds some styling. Although this does introduce some extra whitespace (and could probably be jazzed up a little more), I think it's easier to digest. I'm happy to take input/suggestions if you'd like anything changed! 

Screen Shot 2020-03-06 at 4 13 19 PM

Screen Shot 2020-03-06 at 4 13 23 PM

### CODE REVIEW

**Comment by dmunozc** [comment]
whoops I think we worked on similar stuff for the main dashboard. Your changes are more substantial than mine, so I think we should keep those and then I can redo any changes that I did (if they are still needed) I think we would have to merge my PR first? Not sure how we want to proceed, but everything looks great

**Comment by carissaallen** [comment]
> whoops I think we worked on similar stuff for the main dashboard. Your changes are more substantial than mine, so I think we should keep those and then I can redo any changes that I did (if they are still needed) I think we would have to merge my PR first? Not sure how we want to proceed, but everything looks great

Uh oh! Sorry about that. I created a Trello ticket to try to explain what I was working on to avoid a conflict, but it happens! Maybe we can get @rooneyshuman input on this? I don't want to merge my changes unless you both like the Dashboard appearance. I personally like a little more whitespace and separation, but could also understand if you both wanted to keep everything closer together without having to scroll. I'm happy to go either way.

**Comment by dmunozc** [comment]
I actually only did some responsiveness improvements, the whitespace I think will work better. So I am all for incorporating your changes and then I can redo the small improvements I made

**Comment by dmunozc** [comment]
I am going to cancel my PR and create a new one incorporating these changes, after it is merged

**Review by dmunozc — APPROVED** [review]

**Pull request merged**
