### PR TITLE
Fix footer position so it "sticks" to the bottom of the page

### LINKED ISSUE #8: Footer location does not change as new content is added
On our /portfolio page the charting changes the size of the viewport on load. So the footer is positioned before the full page is rendered.
We need to make our footer 'sticky' to the bottom

footer_problem

### PR DESCRIPTION
**Pull request by carissaallen**
Resolves #8

### CODE REVIEW

**Review by dmunozc — APPROVED** [review]
It works, I will have to adjust some stuff on my end but its great. Thank you!

**Comment by carissaallen** [comment]
> It works, I will have to adjust some stuff on my end but its great. Thank you!

Oh no! What do you have to adjust? If it doesn't look like at a certain screen size or browser, let me know! I'm happy to keep making adjustments.

**Comment by dmunozc** [comment]
There is some overflow happening at the end. I think it might be how my card is set up, or maybe there is some extra margin of padding I can put that will workaround that problem. But does not seems to be a footer issue

footer_problem_2

**Review by rooneyshuman — APPROVED** [review]
Since David agrees the overflow issue is on his end, I'll approve and merge!

**Pull request merged**
