### PR TITLE
Savings progress bar

### PR DESCRIPTION
**Pull request by rooneyshuman**
This PR adds a simple progress bar. The percentage is calculated within the `script` tag of the `index.html` file using the `savings account` balance pulled from the Plaid API and the bar width is adjusted accordingly with JQuery. 

Dashboard view with savings progress bar added:
Screen Shot 2020-02-26 at 8 57 58 PM

### CODE REVIEW

**Review by carissaallen — COMMENTED** [review]
This looks great! When I run your branch locally, however, it looks like this: 

Screen Shot 2020-02-27 at 12 33 34 PM

It shows that the savings goal is $210, and that 42% of the savings goal is $210. So it looks like something may not be working quite right (or I'm doing something wrong on my end).

**Comment by rooneyshuman** [comment]
ohh my bad! I made a commit after I opened the pull request and used the wrong variable name for the savings goal. I'll commit a patch.

**Review by carissaallen — APPROVED** [review]
Progress bar works (and looks) great! 👍

**Review by dmunozc — APPROVED** [review]
looks great, thanks

**Pull request merged**
