### PR TITLE
Portfolio Changes 2

### PR DESCRIPTION
**Pull request by dmunozc**
List of Changes:

- Modified portfolio page so it displays the charts in a more fluid way
- Now we can add as many symbols as we want and the will be charted dynamically
- Added stock twits feed page
- Added .map files to .gitignore (ignores scss compilation mappings)

### CODE REVIEW

**Review by rooneyshuman — CHANGES_REQUESTED** [review]
While I see the candlestick charts running the app locally, they fail to render on deployment. 
This is the error I see on my browser's console:
Screen Shot 2020-02-23 at 6 36 17 PM

Edit: an old version of the `.js` file was cached on my browser causing the error. Everything looks good!

**Comment by rooneyshuman** [comment]
Not sure what exactly is causing the error, but your branch is currently deployed on https://dollar-tracker.herokuapp.com/portfolio if you want to take a look for yourself!

**Comment by dmunozc** [comment]
funny enough the charting seems to be working at https://dollar-tracker.herokuapp.com/portfolio

I think I have seen that error before, can you check that you have the latest changes? Because the current line 8 of portfolio.js has the function `chartStocks` not `drawOHLC`

**Review by rooneyshuman — APPROVED** [review]

**Review by carissaallen — APPROVED** [review]
Looks fantastic! ⚡️

**Pull request merged**
