### PR TITLE
Portfolio 3

### PR DESCRIPTION
**Pull request by dmunozc**
Major Changes:

- Added iexfinance as a dependency to query data from IEX
- Added news feed for portfolio page
- Added 'invesment sector allocation' pie chart to portfolio page
- Tried to make our main page more responsive to screen changes
  - I collapsed our sidebar by default since it was causing problems on mobile screens
- Added initial settings page along with password reset and other pages

### CODE REVIEW

**Review by rooneyshuman — CHANGES_REQUESTED** [review]
There seems to be an inconsistent left alignment with the labels/input elements in the Settings page. See screenshot below:
image
There's a different spacing size for the buttons/labels on each section from the left of the page.

I'm also having issues with the scrolling display of the dropdown menu and the `1 hour` option cannot displayed:
Screen Recording 2020-03-09 at 11 37 56 AM

**Comment by dmunozc** [comment]
Hi Belen, yes I did notice that weird behavior right after I pushed it. I have been trying to figure out why but not sure how to fix it. So I just removed it, and also fixed the weird alignment issues. Please take another look!

**Comment by rooneyshuman** [comment]
Hey, I think it might actually be your use of the `col` class. Here's what I mean about the left alignment:
image

Also, you should probably not be using `fieldset` and `legend` elements at least for the Symbols Tracked and Main User Settings sections since they are meant to be used for grouping related elements in a form, and neither of those contain forms.

**Comment by dmunozc** [comment]
interesting, I will work on it!

**Comment by dmunozc** [comment]
settings2
Settings looking better, removed the weird padding I had around them and fixed the aligment issues. Also removed the fieldset and added an h2 tag to titles. Also added h2 titles to the reset, unlock, and confirmation pages

**Review by rooneyshuman — APPROVED** [review]
Changes look great, David! thanks!

**Pull request merged**
